---
apiVersion: v1
kind: Template
metadata:
  name: service-account-template
objects:
  - apiVersion: v1
    kind: SecurityContextConstraints
    metadata:
      name: jboss-scc
    runAsUser:
      type: MustRunAs
      uid: 185
    seLinuxContext:
      type: MustRunAs
    users:
      - jboss-sa