---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        external: flareclient-server
      name: flareclient-server
    spec:
      ports:
      - nodePort: 0
        port: 8081
        protocol: TCP
        targetPort: 8081
      sessionAffinity: None
      selector:
        name: flareclient-server
      type: ClusterIP
    status:
      loadBalancer: {}