version: '2'
services:
    flareclient-app:
        image: flare/flareclient.backend
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            # - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://flareclient-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=flareclient
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    flareclient-mongodb:
        extends:
            file: mongodb.yml
            service: flareclient-mongodb
